### PR TITLE
fix: landscape layout

### PR DESCRIPTION
**Pull request by SputNikPlop**
This is my WIP on how to fix the landscape layout problem, not sure what other tips you have on this one.

### CODE REVIEW

**Comment by kevmo314** [comment]
> This is my WIP on how to fix the landscape layout problem, not sure what other tips you have on this one.

Screenshot?

**Comment by SputNikPlop** [comment]
> Screenshot?

IMG_3584 Medium

**Comment by kevmo314** [comment]
> > Screenshot?
> 
> IMG_3584 Medium

Nice, this seems like a worthwhile improvement. I'd like to make a few small tweaks to the code also to fix the overflow warning. If I don't get to it by this weekend, bother me on discord.

**Comment by SputNikPlop** [comment]
> Nice, this seems like a worthwhile improvement. I'd like to make a few small tweaks to the code also to fix the overflow warning. If I don't get to it by this weekend, bother me on discord.

Sure, also wasn't sure on how to tackle the UI or the keyboard visibility part but sounds good will follow up next week

**Comment by SputNikPlop** [comment]
Superseded by #1322

**Pull request closed without merging**
