### PR TITLE
fix: template for translations

### PR DESCRIPTION
**Pull request by SputNikPlop**
@juaoose @kevmo314 this is the template file, I don't know how to properly include it though

### CODE REVIEW

**Comment by kevmo314** [comment]
I don't think we should use an explicit template file, it will be a pain to keep in sync with english

**Comment by SputNikPlop** [comment]
> I don't think we should use an explicit template file, it will be a pain to keep in sync with english

What or which way would be best for us to go about making it simple and easy for translators to contribute? Most of our contributors so far use the app but are unfamiliar with the codebase.

**Comment by kevmo314** [comment]
> > I don't think we should use an explicit template file, it will be a pain to keep in sync with english
> 
> What or which way would be best for us to go about making it simple and easy for translators to contribute? Most of our contributors so far use the app but are unfamiliar with the codebase.

We probably can setup a small website that generates the translation table. This would make it easier for people to contribute and I don't think it would be too difficult. I'll add it onto the pile lol

**Comment by SputNikPlop** [comment]
> We probably can setup a small website that generates the translation table. This would make it easier for people to contribute and I don't think it would be too difficult. I'll add it onto the pile lol

Alright added #1017 and will close this issue

**Pull request closed without merging**
