### PR TITLE
Each time after re-openning the app, first message will have timestamp

### PR DESCRIPTION
**Pull request by aminmgh**
I used a simple idea and actually I used a bool variable and for the first time after opening of the app, timestamp that is the exact sent time, will attach to the end of user's message and with that we can track the timeline of chat history beside that only special messages will have timestamps not all of the messages.

### CODE REVIEW

**Comment by kevmo314** [comment]
Wow cool! Do you have a screenshot?

**Comment by aminmgh** [comment]
> Wow cool! Do you have a screenshot?



> Wow cool! Do you have a screenshot?

Sure :)
Here you are:
photo_2021-07-17_00-01-01
but notice that it doesn't look so fancy :/ because I was running out of time.

**Comment by kevmo314** [comment]
Thanks! I think this is a good start. I'd like to tweak the UI to look a bit nicer since every PR triggers a play store release, but I like the idea that the last message after opening will render a timestamp.

Perhaps we can render it on the next line? Also, are you on the discord? I can add you to the dev channel and we can help you out if you don't have much time too.

**Comment by aminmgh** [comment]
> Thanks! I think this is a good start. I'd like to tweak the UI to look a bit nicer since every PR triggers a play store release, but I like the idea that the last message after opening will render a timestamp.
> 
> Perhaps we can render it on the next line? Also, are you on the discord? I can add you to the dev channel and we can help you out if you don't have much time too.

**Comment by aminmgh** [comment]
> Thanks! I think this is a good start. I'd like to tweak the UI to look a bit nicer since every PR triggers a play store release, but I like the idea that the last message after opening will render a timestamp.
> 
> Perhaps we can render it on the next line? Also, are you on the discord? I can add you to the dev channel and we can help you out if you don't have much time too.

You're welcome. 
Yeah I think rendering it in next line will be fine. 
Yes, I'm on the discord by this ID: Aminmgh . It's my pleasure to help you with this issue but I have works to do until next week and after that I'll be free.
Also It's good to say that I took time on this issue because it was a homework of my "Mobile Development" course in university.

**Comment by aminmgh** [comment]
Hi kevmo314 !!!
I resolve another issue of your project tonight, issue #18 
for that I check the last message that is in chat history; if user of that message and user of the message that wants to send now, then I delete the last message in chat history and attach its text to the first part of the message that's ready to send.
Hope it'll be as you wish.

**Comment by kevmo314** [comment]
> Hi kevmo314 !!!
> I resolve another issue of your project tonight, issue #18
> for that I check the last message that is in chat history; if user of that message and user of the message that wants to send now, then I delete the last message in chat history and attach its text to the first part of the message that's ready to send.
> Hope it'll be as you wish.

Thank you! Could you separate that change into a new pull request? It's generally good practice to keep one pull request per feature and we can review that code independently.

Awesome to see you're excited to contribute!

**Comment by aminmgh** [comment]
> > Hi kevmo314 !!!
> > I resolve another issue of your project tonight, issue #18
> > for that I check the last message that is in chat history; if user of that message and user of the message that wants to send now, then I delete the last message in chat history and attach its text to the first part of the message that's ready to send.
> > Hope it'll be as you wish.
> 
> Thank you! Could you separate that change into a new pull request? It's generally good practice to keep one pull request per feature and we can review that code independently.
> 
> Awesome to see you're excited to contribute!

Sorry but I'm not so professional in github and actually I don't know how to do what you asked me. :///

**Comment by kevmo314** [comment]
> Sorry but I'm not so professional in github and actually I don't know how to do what you asked me. :///

That's okay, no worries! Can you create a new branch/fork and move the code you changed for #18 into that branch? Then on GitHub, you can create a new pull request for that feature.

It's generally better to keep one branch per feature to avoid changes getting too complicated. Right now, both features are in the same branch which means if something goes wrong and we need to inspect the code, it'll be difficult to diagnose why something went wrong because a lot more code was affected.

Is that explanation more helpful?

**Comment by aminmgh** [comment]
> > Sorry but I'm not so professional in github and actually I don't know how to do what you asked me. :///
> 
> That's okay, no worries! Can you create a new branch/fork and move the code you changed for #18 into that branch? Then on GitHub, you can create a new pull request for that feature.
> 
> It's generally better to keep one branch per feature to avoid changes getting too complicated. Right now, both features are in the same branch which means if something goes wrong and we need to inspect the code, it'll be difficult to diagnose why something went wrong because a lot more code was affected.
> 
> Is that explanation more helpful?

Hell yeah :))
I got your point completely. I'll do as you say as soon as possible.

**Pull request closed without merging**
